apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocdpoc
  source:
    path: nginx-devportal
    repoURL: https://github.com/ganesh-poc-repo/argocdpoc.git
    targetRevision: HEAD
