apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test123
  namespace: argocd
spec:
  destination:
    namespace: nginx-test
    server: https://kubernetes.default.svc
  project: argocdpoc
  source:
    path: nginx-devportal
    repoURL: https://github.com/ganesh-poc-repo/argocdpoc.git
    targetRevision: HEAD
